export const fonts = {
  h1: {
    fontFamily: "Montserrat",
    fontSize: "34px",
    fontWeight: "700",
    lineHeight: "41.45px",
  },
  h2: {
    fontFamily: "Poppins",
    fontSize: "52px",
    fontWeight: "700",
    lineHeight: "65px",
  },
  h3: {
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "24px",
  },
  h4: {
    fontFamily: "Poppins",
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "24px",
  },
  h5: {
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "24px",
    lineHeight: "36px",
  },
  h6: {
    fontFamily: "Poppins",
    fontWeight: "500",
    fontSize: "16px",
    lineHeight: "24px",
  },
  h7: {
    fontFamily: "Poppins",
    fontWeight: "500",
    fontSize: "14px",
    lineHeight: "21px",
  },
  h8: {
    fontFamily: "Poppins",
    fontWeight: "500",
    fontSize: "18px",
    lineHeight: "24px",
  },
  h9: {
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "32px",
    lineHeight: "48px",
  },
  h10: {
    fontFamily: "Poppins",
    fontWeight: "600",
    fontSize: "24px",
    lineHeight: "36px",
  },
  h11: {
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "40px",
    lineHeight: "48px",
  },
  body1: {
    fontFamily: "Poppins",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "24px",
  },
  body2: {
    fontFamily: "Poppins",
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "21px",
  },
  body3: {
    fontFamily: "Poppins",
    fontWeight: "400",
    fontSize: "20px",
    lineHeight: "30px",
  },
};
