import { Box } from "@mui/material";
import type { Metadata } from "next";
import { AppBarHeader } from "./components/appBarHeader";
import { Footer } from "./components/footer";
import "./globals.css";
import ThemeWrapper from "./themeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeWrapper>
          <Box>
            <AppBarHeader />
            <Box component="main" sx={{ flexGrow: 0, mt: 8 }}>
              <Box>{children}</Box>
            </Box>
            <Footer />
          </Box>
        </ThemeWrapper>
      </body>
    </html>
  );
}
