export type TProduct = {
  id: number;
  title: string;
  img: string;
  description: string;
  price: number;
  discount: number;
  new: boolean;
  sku: string;
  category: string;
  tags: string[];
  size: string[];
  color: string[];
  star: number;
  review: string[];
  info: string;
  room: string;
};

export const productData: TProduct[] = [
  {
    id: 1,
    title: "Syltherine",
    img: "/images/product1.png",
    description: "Stylish cafe chair",
    price: 2500000,
    discount: 0.3,
    new: false,
    sku: "ss001",
    category: "combo",
    tags: ["desk", "chair", "lamp"],
    size: ["S", "M", "L"],
    color: ["white"],
    star: 3,
    review: ["awesome", "nice"],
    info: "This is set. but you can buy one of pieces.",
    room: "dining",
  },
  {
    id: 2,
    title: "Leviosa",
    img: "/images/product2.png",
    description: "Stylish cafe chair",
    price: 2500000,
    discount: 0,
    new: false,
    sku: "ss002",
    category: "chair",
    tags: ["chair"],
    size: ["S", "M", "L"],
    color: ["white", "black"],
    star: 2,
    review: ["too small", "it's hard"],
    info: "made by recycled plastic.",
    room: "dining",
  },
  {
    id: 3,
    title: "Lolito",
    img: "/images/product3.png",
    description: "Luxury big sofa",
    price: 7000000,
    discount: 0.5,
    new: false,
    sku: "ss003",
    category: "sofa",
    tags: ["sofa"],
    size: ["M", "L"],
    color: ["gray", "brown"],
    star: 4,
    review: ["cosy sofa."],
    info: "made by cotton",
    room: "living",
  },
  {
    id: 4,
    title: "Respira",
    img: "/images/product4.png",
    description: "Outdoor bar table and stool",
    price: 500000,
    discount: 0,
    new: true,
    sku: "ss004",
    category: "combo",
    tags: ["sofa", "desk"],
    size: ["L"],
    color: ["gray", "white"],
    star: 4,
    review: ["nice functional raw table."],
    info: "This is set. but you can buy one of pieces.",
    room: "living",
  },
  {
    id: 5,
    title: "Grifo",
    img: "/images/product5.png",
    description: "Night lamp",
    price: 1500000,
    discount: 0,
    new: false,
    sku: "ss005",
    category: "lamp",
    tags: ["lamp"],
    size: ["M"],
    color: ["white"],
    star: 5,
    review: ["good light and using less electricity"],
    info: "height: 150cm",
    room: "living",
  },
  {
    id: 6,
    title: "Muggo",
    img: "/images/product6.png",
    description: "Small mug",
    price: 150000,
    discount: 0,
    new: true,
    sku: "ss006",
    category: "combo",
    tags: ["sofa", "desk"],
    size: ["S", "M"],
    color: ["gray", "black"],
    star: 3,
    review: ["good size and good sprint"],
    info: "for two people",
    room: "living",
  },
  {
    id: 7,
    title: "Pingky",
    img: "/images/product7.png",
    description: "Cute bed set",
    price: 7000000,
    discount: 0.5,
    new: false,
    sku: "ss007",
    category: "combo",
    tags: ["sofa", " desk"],
    size: ["M", "L"],
    color: ["Gray"],
    star: 3,
    review: ["fluffy sofa"],
    info: "for two, three people",
    room: "living",
  },
  {
    id: 8,
    title: "Potty",
    img: "/images/product8.png",
    description: "Minimalist flower pot",
    price: 500000,
    discount: 0,
    new: true,
    sku: "ss008",
    category: "sofa",
    tags: ["sofa"],
    size: ["M"],
    color: ["brown"],
    star: 4,
    review: ["good leather that is not broken easily"],
    info: "leather material",
    room: "living",
  },
];
